import { createSceneControlsStore } from "./scene";

export const DEFAULT_WORK_SCENE_CONTROLS = {
  strip: {
    x: 0,
    y: -1.15,
    z: -4.85,
    rx: 0,
    ry: -Math.PI / 2,
    rz: 0,
    scale: 0.85,
    visibleItems: 7,
    gapSize: 0.035,
    curveRadius: 11.65,
    curveAmount: 1.5,
    stripHeight: 3.7,
    stripYOffset: 0,
    roughness: 0.72,
    sheenR: 0.92,
    sheenG: 0.88,
    sheenB: 0.82,
    subsurfaceStr: 1,
    windStrength: 1.1,
    flutterAmplitude: 0.08,
    flutterFrequency: 20,
    gravityScale: 1.5,
    constraintMix: 0.4,
    wheelSensitivity: 0.0028,
    dragSensitivity: 0.0068,
    dragVelocityScale: 0.0076,
    scrollLerp: 0.11,
    scrollDamping: 0.9,
    scrollDraggingDamping: 0.82,
    snapVelocityThreshold: 0.035,
    snapLerp: 0.18,
    snapEpsilon: 0.0025,
  },
};

export const useWorkSceneControlsStore = createSceneControlsStore(DEFAULT_WORK_SCENE_CONTROLS);
