import { createSceneControlsStore } from "./scene";

/** Baked work-strip pose; Leva position/scale default to identity on top of this. */
export const WORK_STRIP_BASE_TRANSFORM = {
  x: 35,
  y: 22.3,
  z: 51.6,
  scale: 6.9,
} as const;

export const DEFAULT_WORK_SCENE_CONTROLS = {
  strip: {
    x: -3.9,
    y: 1.75,
    z: 1.15,
    rx: 0,
    ry: -Math.PI / 2,
    rz: 0,
    scale: 1,
    visibleItems: 7,
    gapSize: 0.04,
    curveRadius: 4.2,
    curveAmount: 2,
    stripHeight: 1.9,
    stripYOffset: 0,
    windStrength: 1,
    flutterAmplitude: 0.07,
    flutterFrequency: 20.8,
    gravityScale: 1,
    wheelSensitivity: 0.0028,
    dragSensitivity: 0.0068,
    dragVelocityScale: 0.0076,
    scrollLerp: 0.11,
    scrollDamping: 0.9,
    scrollDraggingDamping: 0.82,
    snapVelocityThreshold: 0.035,
    snapLerp: 0.18,
    snapEpsilon: 0.0025,
    exposure: 1,
    levelsInLow: 0,
    levelsInHigh: 1,
    levelsGamma: 1,
    levelsOutLow: 0,
    levelsOutHigh: 1,
    brightness: 1,
    contrast: 1,
    saturation: 1.16,
    shadeMin: 1,
    shadeMax: 1,
    baseLight: 1,
    loosenessLight: 0,
    centerLight: 0,
    rimStrength: 0,
    edgeFade: 0,
    opacity: 1,
    scrollEnabled: true,
  },
};

export const useWorkSceneControlsStore = createSceneControlsStore(DEFAULT_WORK_SCENE_CONTROLS);
