import { createSceneControlsStore } from "./scene";

export const DEFAULT_WORK_SCENE_CONTROLS = {
  strip: {
    // ponytail: matches ROOM_POSES.work.orbitCenterX; nudge y/z in Leva if needed
    x: 37.0,
    y: 17.0,
    z: -12.0,
    rx: (3.0 * Math.PI) / 180,
    ry: 0,
    rz: 0,
    scale: 1.97,
    visibleItems: 7,
    gapSize: 0.04,
    curveRadius: 11,
    curveAmount: 2,
    stripHeight: 4,
    stripYOffset: 0,
    windStrength: 1.04,
    flutterAmplitude: 0.07,
    flutterFrequency: 20.8,
    gravityScale: 1.22,
    wheelSensitivity: 0.0028,
    dragSensitivity: 0.0068,
    dragVelocityScale: 0.0076,
    scrollLerp: 0.11,
    scrollDamping: 0.9,
    scrollDraggingDamping: 0.82,
    snapVelocityThreshold: 0.035,
    snapLerp: 0.18,
    snapEpsilon: 0.0025,
    brightness: 1,
    contrast: 1,
    saturation: 1.152,
    shadeMin: 0.62,
    shadeMax: 0.96,
    baseLight: 0.6,
    loosenessLight: 0,
    centerLight: 0.5,
    rimStrength: 0.04,
    edgeFade: 0,
    opacity: 1,
  },
};

export const useWorkSceneControlsStore = createSceneControlsStore(DEFAULT_WORK_SCENE_CONTROLS);
