// @ts-nocheck
import React from "react";
import { Leva, button, folder, useControls } from "leva";
import { defaultTestSceneControls, useTestSceneControlsStore } from "../../store/testSceneControls";

const DEFAULTS = defaultTestSceneControls();

export default function TestSceneControls() {
  const controls = useTestSceneControlsStore();
  const patch = useTestSceneControlsStore((state) => state.patch);
  const reset = useTestSceneControlsStore((state) => state.reset);

  useControls(
    () => ({
      Camera: folder({
        enableOrbitControls: {
          label: "Orbit Controls",
          value: controls.enableOrbitControls,
          onChange: (value) => patch({ enableOrbitControls: value }),
        },
        cameraFov: {
          label: "FOV",
          min: 20,
          max: 100,
          step: 0.1,
          value: controls.cameraFov,
          onChange: (value) => patch({ cameraFov: value }),
        },
        cameraPosX: {
          label: "Camera X",
          min: -12,
          max: 12,
          step: 0.01,
          value: controls.cameraPosX,
          onChange: (value) => patch({ cameraPosX: value }),
        },
        cameraPosY: {
          label: "Camera Y",
          min: -6,
          max: 12,
          step: 0.01,
          value: controls.cameraPosY,
          onChange: (value) => patch({ cameraPosY: value }),
        },
        cameraPosZ: {
          label: "Camera Z",
          min: -12,
          max: 18,
          step: 0.01,
          value: controls.cameraPosZ,
          onChange: (value) => patch({ cameraPosZ: value }),
        },
        orbitCenterX: {
          label: "Rig Center X",
          min: -8,
          max: 8,
          step: 0.01,
          value: controls.orbitCenterX,
          onChange: (value) => patch({ orbitCenterX: value }),
        },
        orbitCenterY: {
          label: "Rig Center Y",
          min: -8,
          max: 8,
          step: 0.01,
          value: controls.orbitCenterY,
          onChange: (value) => patch({ orbitCenterY: value }),
        },
        orbitCenterZ: {
          label: "Rig Center Z",
          min: -8,
          max: 8,
          step: 0.01,
          value: controls.orbitCenterZ,
          onChange: (value) => patch({ orbitCenterZ: value }),
        },
        orbitRadius: {
          label: "Rig Radius",
          min: 1,
          max: 12,
          step: 0.01,
          value: controls.orbitRadius,
          onChange: (value) => patch({ orbitRadius: value }),
        },
        orbitTargetX: {
          label: "Target X",
          min: -8,
          max: 8,
          step: 0.01,
          value: controls.orbitTargetX,
          onChange: (value) => patch({ orbitTargetX: value }),
        },
        orbitTargetY: {
          label: "Target Y",
          min: -8,
          max: 8,
          step: 0.01,
          value: controls.orbitTargetY,
          onChange: (value) => patch({ orbitTargetY: value }),
        },
        orbitTargetZ: {
          label: "Target Z",
          min: -8,
          max: 8,
          step: 0.01,
          value: controls.orbitTargetZ,
          onChange: (value) => patch({ orbitTargetZ: value }),
        },
        orbitMinDistance: {
          label: "Min Distance",
          min: 0.5,
          max: 24,
          step: 0.01,
          value: controls.orbitMinDistance,
          onChange: (value) => patch({ orbitMinDistance: value }),
        },
        orbitMaxDistance: {
          label: "Max Distance",
          min: 1,
          max: 32,
          step: 0.01,
          value: controls.orbitMaxDistance,
          onChange: (value) => patch({ orbitMaxDistance: value }),
        },
        orbitMinPolarAngle: {
          label: "Min Polar",
          min: 0,
          max: 180,
          step: 1,
          value: controls.orbitMinPolarAngle,
          onChange: (value) => patch({ orbitMinPolarAngle: value }),
        },
        orbitMaxPolarAngle: {
          label: "Max Polar",
          min: 0,
          max: 180,
          step: 1,
          value: controls.orbitMaxPolarAngle,
          onChange: (value) => patch({ orbitMaxPolarAngle: value }),
        },
      }),
      Placement: folder({
        modelScale: {
          label: "Scale",
          min: 1,
          max: 24,
          step: 0.01,
          value: controls.modelScale,
          onChange: (value) => patch({ modelScale: value }),
        },
        modelPosX: {
          label: "Model X",
          min: -8,
          max: 8,
          step: 0.01,
          value: controls.modelPosX,
          onChange: (value) => patch({ modelPosX: value }),
        },
        modelPosY: {
          label: "Model Y",
          min: -8,
          max: 8,
          step: 0.01,
          value: controls.modelPosY,
          onChange: (value) => patch({ modelPosY: value }),
        },
        modelPosZ: {
          label: "Model Z",
          min: -8,
          max: 8,
          step: 0.01,
          value: controls.modelPosZ,
          onChange: (value) => patch({ modelPosZ: value }),
        },
        modelRotX: {
          label: "Rotate X",
          min: -180,
          max: 180,
          step: 1,
          value: controls.modelRotX,
          onChange: (value) => patch({ modelRotX: value }),
        },
        modelRotY: {
          label: "Rotate Y",
          min: -180,
          max: 180,
          step: 1,
          value: controls.modelRotY,
          onChange: (value) => patch({ modelRotY: value }),
        },
        modelRotZ: {
          label: "Rotate Z",
          min: -180,
          max: 180,
          step: 1,
          value: controls.modelRotZ,
          onChange: (value) => patch({ modelRotZ: value }),
        },
      }),
      Lighting: folder({
        exposure: {
          label: "Exposure",
          min: 0.25,
          max: 2,
          step: 0.01,
          value: controls.exposure,
          onChange: (value) => patch({ exposure: value }),
        },
        directionalIntensity: {
          label: "Key Intensity",
          min: 0,
          max: 6,
          step: 0.01,
          value: controls.directionalIntensity,
          onChange: (value) => patch({ directionalIntensity: value }),
        },
        directionalX: {
          label: "Key X",
          min: -16,
          max: 16,
          step: 0.1,
          value: controls.directionalX,
          onChange: (value) => patch({ directionalX: value }),
        },
        directionalY: {
          label: "Key Y",
          min: -4,
          max: 16,
          step: 0.1,
          value: controls.directionalY,
          onChange: (value) => patch({ directionalY: value }),
        },
        directionalZ: {
          label: "Key Z",
          min: -16,
          max: 16,
          step: 0.1,
          value: controls.directionalZ,
          onChange: (value) => patch({ directionalZ: value }),
        },
        ambientIntensity: {
          label: "Ambient",
          min: 0,
          max: 2,
          step: 0.01,
          value: controls.ambientIntensity,
          onChange: (value) => patch({ ambientIntensity: value }),
        },
        fillIntensity: {
          label: "Fill",
          min: 0,
          max: 2,
          step: 0.01,
          value: controls.fillIntensity,
          onChange: (value) => patch({ fillIntensity: value }),
        },
        rimIntensity: {
          label: "Rim",
          min: 0,
          max: 2,
          step: 0.01,
          value: controls.rimIntensity,
          onChange: (value) => patch({ rimIntensity: value }),
        },
        accentIntensity: {
          label: "Accent",
          min: 0,
          max: 2,
          step: 0.01,
          value: controls.accentIntensity,
          onChange: (value) => patch({ accentIntensity: value }),
        },
      }),
      Material: folder({
        roughnessScale: {
          label: "Roughness",
          min: 0.1,
          max: 2,
          step: 0.01,
          value: controls.roughnessScale,
          onChange: (value) => patch({ roughnessScale: value }),
        },
        metalnessScale: {
          label: "Metalness",
          min: 0,
          max: 2,
          step: 0.01,
          value: controls.metalnessScale,
          onChange: (value) => patch({ metalnessScale: value }),
        },
        envReflection: {
          label: "Env Reflection",
          min: 0,
          max: 3,
          step: 0.01,
          value: controls.envReflection,
          onChange: (value) => patch({ envReflection: value }),
        },
        clearcoat: {
          label: "Clearcoat",
          min: 0,
          max: 1,
          step: 0.01,
          value: controls.clearcoat,
          onChange: (value) => patch({ clearcoat: value }),
        },
        clearcoatRoughness: {
          label: "Clearcoat Roughness",
          min: 0,
          max: 1,
          step: 0.01,
          value: controls.clearcoatRoughness,
          onChange: (value) => patch({ clearcoatRoughness: value }),
        },
      }),
      Actions: folder({
        resetAll: button(() => reset()),
        resetPlacement: button(() =>
          patch({
            modelScale: DEFAULTS.modelScale,
            modelPosX: DEFAULTS.modelPosX,
            modelPosY: DEFAULTS.modelPosY,
            modelPosZ: DEFAULTS.modelPosZ,
            modelRotX: DEFAULTS.modelRotX,
            modelRotY: DEFAULTS.modelRotY,
            modelRotZ: DEFAULTS.modelRotZ,
          }),
        ),
      }),
    }),
    [
      controls.enableOrbitControls,
      controls.cameraFov,
      controls.cameraPosX,
      controls.cameraPosY,
      controls.cameraPosZ,
      controls.orbitCenterX,
      controls.orbitCenterY,
      controls.orbitCenterZ,
      controls.orbitRadius,
      controls.orbitTargetX,
      controls.orbitTargetY,
      controls.orbitTargetZ,
      controls.orbitMinDistance,
      controls.orbitMaxDistance,
      controls.orbitMinPolarAngle,
      controls.orbitMaxPolarAngle,
      controls.modelScale,
      controls.modelPosX,
      controls.modelPosY,
      controls.modelPosZ,
      controls.modelRotX,
      controls.modelRotY,
      controls.modelRotZ,
      controls.exposure,
      controls.directionalIntensity,
      controls.directionalX,
      controls.directionalY,
      controls.directionalZ,
      controls.ambientIntensity,
      controls.fillIntensity,
      controls.rimIntensity,
      controls.accentIntensity,
      controls.roughnessScale,
      controls.metalnessScale,
      controls.envReflection,
      controls.clearcoat,
      controls.clearcoatRoughness,
      patch,
      reset,
    ],
  );

  return (
    <Leva
      oneLineLabels
      flat={false}
      titleBar={{ title: "Test Scene Controls", drag: true, filter: false }}
      theme={{
        sizes: {
          rootWidth: "min(360px, calc(100vw - 24px))",
          controlWidth: "150px",
        },
      }}
    />
  );
}
