/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/logo.glb -o src/models/LogoModel.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function LogoModel(props) {
  const { nodes, materials } = useGLTF('/models/logo.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_0.geometry} material={materials['Car chrome']} scale={0.526} />
    </group>
  )
}

useGLTF.preload('/models/logo.glb')
