// @ts-nocheck
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/logo.glb -o src/models/LogoModel.jsx 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { gltfLoaderOptions } from "./gltfLoaderOptions";
import { GLTF_URL_LOGO } from "./gltfUrls";

/* eslint-disable react/no-unknown-property */
export default function LogoModel(props) {
  const { nodes, materials } = useGLTF(GLTF_URL_LOGO, gltfLoaderOptions);
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_0.geometry} material={materials["Car chrome"]} scale={0.526} />
    </group>
  );
}
