// @ts-nocheck
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/monitor.glb -o src/models/MonitorModel.jsx 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { gltfLoaderOptions } from "./gltfLoaderOptions";
import { GLTF_URL_MONITOR } from "./gltfUrls";

export function Model(props) {
  const { nodes, materials } = useGLTF(GLTF_URL_MONITOR, gltfLoaderOptions);
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.016}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            geometry={nodes.monitor002_low_monitor_0.geometry}
            material={materials.monitor}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.monitor_low_monitor_0.geometry}
            material={materials.monitor}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.monitor003_low_monitor_0.geometry}
            material={materials.monitor}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.monitor004_low_monitor_0.geometry}
            material={materials.monitor}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.monitor005_low_monitor_0.geometry}
            material={materials.monitor}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.monitor006_low_monitor_0.geometry}
            material={materials.monitor}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.monitor007_low_monitor_0.geometry}
            material={materials.monitor}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.monitor001_low_monitor_0.geometry}
            material={materials.monitor}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
    </group>
  );
}
