/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/project-bg.glb -o src/models/ProjectBgModel.jsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { gltfLoaderOptions } from "./gltfLoaderOptions.js";
import { GLTF_URL_PROJECT_BG } from "./gltfUrls.js";

/* eslint-disable react/no-unknown-property */
export function ProjectBgModel(props) {
  const { nodes, materials } = useGLTF(GLTF_URL_PROJECT_BG, gltfLoaderOptions);
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.bird_01.geometry} material={materials["mat-bird"]} />
      <mesh
        geometry={nodes.bird_01001.geometry}
        material={materials["mat-bird"]}
        position={[13.249, -19.966, 0]}
      />
      <mesh
        geometry={nodes.bird_01002.geometry}
        material={materials["mat-bird"]}
        position={[-13.261, -39.989, 0]}
      />
      <mesh
        geometry={nodes.deer_01.geometry}
        material={materials["mat-deer"]}
        position={[-0.146, -9.818, 0]}
      />
      <mesh
        geometry={nodes.deer_01001.geometry}
        material={materials["mat-deer"]}
        position={[13.1, 0.167, 0]}
      />
      <mesh
        geometry={nodes.deer_01002.geometry}
        material={materials["mat-deer"]}
        position={[13.1, -29.841, 0]}
      />
      <mesh
        geometry={nodes.deer_01003.geometry}
        material={materials["mat-deer"]}
        position={[-13.406, -49.872, 0]}
      />
      <mesh
        geometry={nodes.dragonflies_01.geometry}
        material={materials["mat-dragonflies"]}
        position={[0, -20.038, 0]}
      />
      <mesh
        geometry={nodes.dragonflies_01001.geometry}
        material={materials["mat-dragonflies"]}
        position={[-13.248, -10.056, 0]}
      />
      <mesh
        geometry={nodes.dragonflies_01002.geometry}
        material={materials["mat-dragonflies"]}
        position={[13.243, -40.065, 0]}
      />
      <mesh
        geometry={nodes.frog_01.geometry}
        material={materials["mat-frog"]}
        position={[0.033, -49.628, 0]}
      />
      <mesh
        geometry={nodes.frog_01001.geometry}
        material={materials["mat-frog"]}
        position={[-12.126, 0.27, 0]}
      />
      <mesh
        geometry={nodes.frog_01002.geometry}
        material={materials["mat-frog"]}
        position={[-13.223, -29.654, 0]}
      />
      <mesh
        geometry={nodes.peacock_01001.geometry}
        material={materials["mat-peacock"]}
        position={[13.292, -10.341, 0]}
      />
      <mesh
        geometry={nodes.peacock_01002.geometry}
        material={materials["mat-peacock"]}
        position={[13.289, -50.34, 0]}
      />
      <mesh
        geometry={nodes.peacock_v02.geometry}
        material={materials["mat-peacock"]}
        position={[0.035, -40.353, 0]}
      />
      <mesh
        geometry={nodes.squirrel_01.geometry}
        material={materials["mat-squirrel"]}
        position={[0.036, -30.01, 0]}
      />
      <mesh
        geometry={nodes.squirrel_01001.geometry}
        material={materials["mat-squirrel"]}
        position={[-13.209, -19.969, 0]}
      />
    </group>
  );
}
