/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/work.glb -o src/models/WorkModel.jsx 
Author: ChristyHsu (https://sketchfab.com/ida61xq)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/white-round-exhibition-gallery-a443b8a0a2314a55ae5dee4dd6a151a0
Title: White round exhibition gallery
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

/* eslint-disable react/no-unknown-property */
export default function WorkModel(props) {
  const { nodes, materials } = useGLTF("/models/work.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cylinder__0.geometry}
        material={materials.Cylinder__0}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[13.275, 13.275, 5.019]}
      />
      <mesh
        geometry={nodes.Cylinder014_Material001_0.geometry}
        material={materials["Material.001"]}
        position={[0, 4.442, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={[-21.405, 21.405, 0.414]}
      />
    </group>
  );
}
